on: push
name: TOC Generate
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt install gawk -y
          echo "Creating per file TOC"
          find . -name \*.md -exec bash -c "cat {} | ./gh-md-toc {}" \;
          echo "Creating README TOC"
          find . -maxdepth 1 -name \*.md -not -name README.md | sort -n | xargs cat | ./gh-md-toc README.md
          echo "Cleaning up"
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Table of Contents
