on: push
name: TOC Generate
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.9.1/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          echo "Creating per file TOC"
          find . -name \*.md -exec ./gh-md-toc --insert --no-backup --hide-footer --skip-header {} \;
          echo "Creating README TOC"
          ./gen-readme.sh
          echo "Cleaning up"
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Table of Contents
