on: push
name: TOC Generate
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          find . -name \*.md -exec ./gh-md-toc --insert --skip-header --no-backup --hide-footer {} \;
          ./gh-md-toc --no-backup --hide-footer *.md > README.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Table of Contents
